design_task:
  description: >
    Generate a JSON project plan (modules/classes) from the requirements.
  expected_output: >
    Valid JSON following ProjectSpec schema.
  agent: engineering_lead
  output_file: output/project_plan.json
